# Generated by Django 4.2.28 on 2026-09-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('activity_type', models.CharField(choices=[('event', 'Event'), ('project', 'Project'), ('publication', 'Publication'), ('other', 'Other')], default='event', max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='activities/')),
                ('link', models.URLField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', 'display_order'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.FileField(blank=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='mediamention',
            name='image',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.FileField(blank=True, upload_to='partners/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.FileField(blank=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mediamention',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
