# Generated by Django 6.1.1 on 2026-09-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_project_content_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.CharField(blank=True, help_text='For example: “fundraising target — €70,000”.', max_length=180),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_label',
            field=models.CharField(blank=True, help_text='Free text supports date ranges and notes, for example: “11–12 September 2026 (festival runs 9–16 September)”.', max_length=120, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='The main text shown after visitors open “More details”.', verbose_name='Full description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.TextField(blank=True, help_text='Shown in the project facts on the full page.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='outcome',
            field=models.TextField(blank=True, help_text='Optional result, award, or next milestone.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.TextField(blank=True, help_text='Separate names with commas.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='partners',
            field=models.TextField(blank=True, help_text='Separate names with commas.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(help_text='Short text shown on the project card.', verbose_name='Card description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='website_text',
            field=models.TextField(blank=True, help_text='A highlighted editorial note displayed on the full project page.', verbose_name='Website text'),
        ),
    ]
